# BCM2835 Platform Support
ccflags-y += -I$(src)
snd-soc-bcm2835-i2s-objs := bcm2835-i2s.o

obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-i2s.o

# CYGNUS Platform Support
snd-soc-cygnus-objs := cygnus-pcm.o cygnus-ssp.o

obj-$(CONFIG_SND_SOC_CYGNUS) += snd-soc-cygnus.o

