#fingerprint_detect should before fpc1022
ccflags-y += -I$(src)
obj-$(CONFIG_FINGERPRINT_DETECT)    += fingerprint_detect/
obj-$(CONFIG_FINGERPRINT_FPC)	    += fpc/
obj-$(CONFIG_FINGERPRINT_GOODIX)	+= goodix/
obj-$(CONFIG_FINGERPRINT_SILEAD)	+= silead/
